ClientHost: "localhost:5498"
ServerHost: "localhost:5499"
ServerExpiration: 10m
StaticEntries:
  - Name: -----========================-----
    Description:
    Address: 127.0.0.1:0001
  - Name: "Magnetron Static Servers"
    Description:
    Address: 127.0.0.1:0001
  - Name: -----========================-----
    Description:
    Address: 127.0.0.1:0001
EnablePasswords: false
PasswordFile: "./passwords.yml"
TrackerFederation:
  Enabled: false
  PollFrequency: 5m
  Header: "--=Federated Servers=--"
  Trackers:
    - Address: "localhost:5498"
      Name: "Sample loop back"
RestApi:
  Enabled: false
  Host: "localhost:8080"
  EnableTls: false
  CertFile: cert.pem
  KeyFile: key.pem
  EnableTokenAuth: false
  TokenAuthFile: "./tokens.yml"
  
